openapi: 3.0.2
info:
  title: 'friends-service'
  description: "Сервис для добавления людей в друзья"
  version: ''
paths:
  /api/v1/friends/requests/incoming:
    get:
      operationId: listincoming_requests
      description: 'Входящие заявки в друзья'
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Request'
          description: ''
      tags:
        - api
  /api/v1/friends/requests/outgoing:
    get:
      operationId: listoutgoing_requests
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - api
  /api/v1/friends/all_friends:
    get:
      operationId: listall_friends
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - api
  /api/v1/friends/check_status:
    get:
      operationId: listcheck_status
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - api
  /auth/register:
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
        - auth
  /auth/token/login:
    post:
      operationId: createAuthToken
      description: ''
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
      tags:
        - auth
  /api/v1/friends/requests/send:
    post:
      operationId: createsend_request
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
        - api
  /api/v1/friends/requests/accept:
    post:
      operationId: createaccept
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
        - api
  /api/v1/friends/requests/decline:
    post:
      operationId: createdecline
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
        - api
  /api/v1/friends/delete:
    delete:
      operationId: destroydelete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - api
components:
  schemas:
    Request:
      type: object
      properties:
        id:
          type: integer
          readOnly: true

    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        to_user:
          type: int
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        password:
          type: string
          writeOnly: true
      required:
        - username
        - password
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
        - username
        - password
