openapi: 3.0.2
info:
  title: 'friends-service'
  description: "Сервис для добавления людей в друзья. Все руты /api требуют токен юзера"
  version: ''
paths:
  /api/v1/friends/requests/incoming:
    get:
      operationId: listincoming_requests
      description: 'Incoming friendship requests'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserNoPassword'
          description: 'OK'
        '204':
          description: 'No incoming requests'
      tags:
      - api/v1/friends/requests
  /api/v1/friends/requests/outgoing:
    get:
      operationId: listoutgoing_requests
      description: 'Outgoing friendship requests'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserNoPassword'
          description: 'OK'
        '204':
          description: 'No outgoing requests'
      tags:
      - api/v1/friends/requests
  /api/v1/friends/requests/send:
    post:
      operationId: createsend_request
      description: 'Send friendship request'
      parameters:
        - name: id
          in: query
          description: 'id of user to send request to'
          required: true
          schema:
            type: integer
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'OK'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
        - api/v1/friends/requests
  /api/v1/friends/requests/accept:
    post:
      operationId: createaccept_request
      description: 'Accept friendship request'
      parameters:
        - name: id
          in: query
          description: 'id of user to accept request from'
          required: true
          schema:
            type: integer
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'OK'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
        - api/v1/friends/requests
  /api/v1/friends/requests/decline:
    post:
      operationId: createdecline_request
      description: 'Decline friendship request'
      parameters:
        - name: id
          in: query
          description: 'id of user to decline request from'
          required: true
          schema:
            type: integer
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'OK'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
        - api/v1/friends/requests
  /api/v1/friends/all:
    get:
      operationId: listall_friends
      description: 'Get all friends'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
          description: 'Friends'
        '204':
          description: 'No friends'
      tags:
      - api/v1/friends
  /api/v1/friends/check_status:
    get:
      operationId: listcheck_status
      description: 'Check if user is friend/requested/etc.'
      parameters:
        - name: id
          in: query
          description: 'id of user to check info about'
          required: true
          schema:
            type: integer
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'OK'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'Not OK'
      tags:
      - api/v1/friends
  /api/v1/friends/delete:
    delete:
      operationId: destroydelete
      description: 'Delete from friends'
      parameters:
        - name: id
          in: query
          description: 'id of user to check info about'
          required: true
          schema:
            type: integer
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'OK'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          description: 'Not OK'
      tags:
        - api/v1/friends
  /auth/register:
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - auth
  /auth/token/login:
    post:
      operationId: createAuthToken
      description: ''
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
      tags:
      - auth
components:
  schemas:
    Result:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
    UserNoPassword:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        password:
          type: string
          writeOnly: true
      required:
      - username
      - password
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - username
      - password
